# configs/trainer/gpu.yaml
_target_: lightning.pytorch.trainer.Trainer
default_root_dir: ${paths.log_dir}/train/runs
min_epochs: 10
max_epochs: 30
accelerator: gpu
devices: 1
check_val_every_n_epoch: 1
deterministic: false