_target_: src.models.orchid_module.OrchidLitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 5

net:
  _target_: src.models.components.orchid_models.OrchidModel
  model_name: inception_v3
  num_classes: 10
  pretrained: true
  freeze_backbone: false

# compile model for faster training with pytorch 2.0
compile: false
num_classes: 10