_target_: src.models.orchid_module.OrchidLitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.00005
  weight_decay: 0.05

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 3

net:
  _target_: src.models.components.orchid_models.OrchidModel
  model_name: mae_vit
  num_classes: 10
  pretrained: true
  freeze_backbone: false

# compile model for faster training with pytorch 2.0
compile: True
num_classes: 10